### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by turbotankist** [leominov/prometheus-devops-linter#1]
При запуске линтера на rules
find ./kustomize/base/configs/rules \( -name "*.yml" -o -name "*.yaml" \) | xargs prometheus-devops-linter rules
вываливается ошибка:
```
time="2019-02-20T10:21:57Z" level=info msg="Starting prometheus-devops-linter (version=1.3.4, branch=master, revision=b5963680f402561e307c687cce11010192c369bd)..."
time="2019-02-20T10:21:57Z" level=info msg="Configuration path: "
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54bc86]

goroutine 1 [running]:
github.com/leominov/prometheus-devops-linter/linter.(*Config).SetDefaults(0x0)
	/go/src/github.com/leominov/prometheus-devops-linter/linter/config.go:48 +0x26
github.com/leominov/prometheus-devops-linter/linter.NewConfig(0x0, 0x0, 0x1, 0xc000136050, 0xc000161e08)
	/go/src/github.com/leominov/prometheus-devops-linter/linter/config.go:40 +0x3b
github.com/leominov/prometheus-devops-linter/linter.NewMetaLinter(0x0, 0x0, 0xc000161f28, 0x1, 0x1)
	/go/src/github.com/leominov/prometheus-devops-linter/linter/meta_linter.go:18 +0x39
main.main()
	/go/src/github.com/leominov/prometheus-devops-linter/main.go:81 +0x1ac
ERROR: Job failed: exit code 123
```
при этом сами правила корректы, т.к. promtool их валидирует
```
$ promtool check rules kustomize/base/configs/rules/*
Checking kustomize/base/configs/rules/kube.yaml
  SUCCESS: 14 rules found

Checking kustomize/base/configs/rules/prometheus.yaml
  SUCCESS: 3 rules found
```

**Comment by leominov** [comment]
@turbotankist скинь примеры конфигов для воскпроизмедения

**Comment by turbotankist** [comment]
дело не в конфигах, сам бинарник падает даже без них...
```
bash-4.4# prometheus-devops-linter rules
INFO[0000] Starting prometheus-devops-linter (version=1.3.4, branch=master, revision=b5963680f402561e307c687cce11010192c369bd)... 
INFO[0000] Configuration path:                          
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x54bc86]

goroutine 1 [running]:
github.com/leominov/prometheus-devops-linter/linter.(*Config).SetDefaults(0x0)
        /go/src/github.com/leominov/prometheus-devops-linter/linter/config.go:48 +0x26
github.com/leominov/prometheus-devops-linter/linter.NewConfig(0x0, 0x0, 0x1, 0xc000130050, 0xc00003be08)
        /go/src/github.com/leominov/prometheus-devops-linter/linter/config.go:40 +0x3b
github.com/leominov/prometheus-devops-linter/linter.NewMetaLinter(0x0, 0x0, 0xc00003bf28, 0x1, 0x1)
        /go/src/github.com/leominov/prometheus-devops-linter/linter/meta_linter.go:18 +0x39
main.main()
        /go/src/github.com/leominov/prometheus-devops-linter/main.go:81 +0x1ac

bash-4.4# prometheus-devops-linter --version
(version=1.3.4, branch=master, revision=b5963680f402561e307c687cce11010192c369bd)
(go=go1.11.3, user=root@312f387ed302, date=20181226-08:13:29)
```
контейнер - просто скопированный твой с нексуса

**Comment by leominov** [comment]
Fix в v1.3.5 – 
https://github.com/leominov/prometheus-devops-linter/releases/tag/v1.3.5
